#!/bin/bash
apt-get update && apt-get upgrade -y
apt-get install stunnel4 -y

openssl genrsa -out key.pem 2048
openssl req -new -x509 -key key.pem -out cert.pem -days 1095
cat key.pem cert.pem >> /etc/stunnel/stunnel.pem

cat >  /etc/stunnel/stunnel.conf << ENDOFFILE
cert = /etc/stunnel/stunnel.pem
client =no

[ssh]
accept = 443
connect = 127.0.0.1:22
ENDOFFILE

/etc/init.d/stunnel4 restart

nano /etc/default/stunnel4

