#!/bin/bash
apt update && apt upgrade -y
apt install sudo curl bash
apt install cmake -y
apt install screen wget gcc build-essential g++ make -y
wget https://github.com/megaster1/kendim/raw/main/badvpn.tar.gz
tar xf badvpn.tar.gz
cd badvpn/
cmake ~/badvpn -DBUILD_NOTHING_BY_DEFAULT=1 -DBUILD_UDPGW=1
make install
badvpn-udpgw --listen-addr 127.0.0.1:7300 > /dev/null &
rm /root/badvpn && rm /root/badvpn.tar.gz

cat >  /etc/systemd/system/videocall.service << ENDOFFILE
[Unit]
Description=UDP forwarding for badvpn-tun2socks
After=nss-lookup.target

[Service]
ExecStart=/usr/local/bin/badvpn-udpgw --loglevel none --listen-addr 127.0.0.1:7300 --max-clients 999
User=videocall

[Install]
WantedBy=multi-user.target
ENDOFFILE
useradd -m videocall
systemctl enable videocall
systemctl start videocall

cd
apt install stunnel

cat >  /etc/stunnel/stunnel.conf << ENDOFFILE
cert = /etc/stunnel/stunnel.pem
client =no

[ssh]
accept = 443
connect = 127.0.0.1:22
ENDOFFILE

openssl genrsa -out key.pem 2048
openssl req -new -x509 -key key.pem -out cert.pem -days 1095
cat key.pem cert.pem >> /etc/stunnel/stunnel.pem

nano /etc/default/stunnel4
